# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://richlewis.com
title: RichLewis.com
email: your-email@domain.com
author: Rich Lewis
description: > # "This is the description in the config file."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/RichLewis007
  - title: github
    url: https://github.com/RichLewis007
  - title: linkedin
    url: https://linkedin.com/RichLewis007
