site_name: "Rich Lewis' Free/Libre and Open-Source Software"
docs_dir: gh-pages-source-docs
site_url: https://richlewis007.com/

theme:
  name: material

# Navigation: mix of local docs and external links
nav:
  - Home: index.md
  - Public gists: https://richlewis007.com/Public-Gists-from-Rich-Lewis/
  - FLOSS Blog: https://blog.richlewis007.com/

# Extra scripts (optional)
extra_javascript:
  - js/nav-newtab.js