site_name: Rich Lewis
site_url: https://github.richlewis007.com/
theme:
  name: material   # change/remove if you don't want Material
nav:
  - Home: index.md
  - Public Gists: /public-gists-from-Rich-Lewis/
  # Use a full URL so Material shows the “external link” icon:
  # - Public Gists: https://github.richlewis007.com/public-gists-from-Rich-Lewis/
  # (If you prefer a domain-agnostic path, you can use /public-gists-from-Rich-Lewis/ instead.)
  # - Blog: https://blog.richlewis007.com/

extra_javascript:
  - js/nav-newtab.js
