site_name: Rich Lewis' Free/Libre and Open-Source Software 
site_url: https://richlewis007.com/
theme:
  name: material
nav:
  - Home: index.md
  - Public gists: /Public-gists-from-Rich-Lewis/
  # Use a full URL so Material shows the “external link” icon:
  - Public gists: https://richlewis007.com/Public-gists-from-Rich-Lewis/
  # (If you prefer a domain-agnostic path, you can use /Public-gists-from-Rich-Lewis/ instead.)
  - FLOSS Blog: https://blog.richlewis007.com/

extra_javascript:
  - js/nav-newtab.js
